---
name: Haskell CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: apt
        env:
          GHCUP_VERSION: 0.1.50.2
          GHC_VERSION: 9.6.7
          CABAL_VERSION: 3.14.2.0
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gnupg ca-certificates dirmngr curl git software-properties-common libtinfo6
          mkdir -p "$HOME/.ghcup/bin"
          curl -sL https://downloads.haskell.org/ghcup/$GHCUP_VERSION/x86_64-linux-ghcup-$GHCUP_VERSION > "$HOME/.ghcup/bin/ghcup"
          sudo chmod a+x "$HOME/.ghcup/bin/ghcup"
          "$HOME/.ghcup/bin/ghcup" install ghc $GHC_VERSION || (cat "$HOME"/.ghcup/logs/*.* && false)
          "$HOME/.ghcup/bin/ghcup" install cabal $CABAL_VERSION || (cat "$HOME"/.ghcup/logs/*.* && false)

      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks

      - name: Build
        run: cabal build --enable-tests --enable-benchmarks all

      - name: Install diagrams
        run: |
          sudo apt-get install -y --no-install-recommends pikchr-cli graphviz gnuplot-x11

      - name: Run tests
        run: cabal test all
